name: gtk_flutter
description: "Get to know Firebase with Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  firebase_core: ^2.32.0
  firebase_auth: ^4.13.0
  firebase_auth_web: ^5.9.0  # Make sure this is up-to-date
  cloud_firestore: ^4.14.1
  provider: ^6.0.5
  google_fonts: ^6.1.0
  go_router: ^12.0.0
  google_sign_in: ^6.3.0

  # Remove flutterfire_cli from here - it's a dev tool

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutterfire_cli: ^1.2.0  # Moved to dev_dependencies

flutter:
  uses-material-design: true
  assets:
    - assets/codelab.png